<?php 

/**
 * Implements hook_menu().
 */
function islandora_marcxml_menu() {
  return array(
    'islandora/object/%islandora_object/view/mods_as_marcxml' => array(
      'title' => 'MARCXML',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_marcxml_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_marcxml_access_callback',
      'access arguments' => array(2),
      'file' => 'islandora_marcxml.inc',
    ),
    'islandora/object/%islandora_object/download/mods_as_marcxml' => array(
      'title' => 'Download MARCXML',
      'type' => MENU_CALLBACK,
      'page callback' => 'islandora_marcxml_transform_mods_to_marcxml',
      'page arguments' => array(2),
      'access callback' => 'islandora_marcxml_access_callback',
      'access arguments' => array(2),
      'delivery callback' => 'islandora_marcxml_xml_download',
      'file' => 'islandora_marcxml.inc',
    ),
  );
}

/**
 * Download the output as XML.
 */
function islandora_marcxml_xml_download($output) {
  drupal_add_http_header('Content-type', 'text/xml;charset=utf8');
  drupal_add_http_header('Content-length', strlen($output));
  drupal_add_http_header('Content-Disposition', 'attachment; filename="marc.xml"');

  print $output;

  drupal_page_footer();
}

function islandora_marcxml_access_callback($object) {
  if (!$object) {
    return FALSE;
  }

  return user_access(FEDORA_VIEW) && isset($object['MODS']);
}
