<?php 

/**
 * Implements hook_menu().
 */
function islandora_marcxml_menu() {
  return array(
    'islandora/object/%islandora_object/view_mods_as_marcxml' => array(
      'title' => 'MARCXML',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_marcxml_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_marcxml_access_callback',
      'access arguments' => array(2),
      'file' => 'islandora_marcxml.inc',
    ),
    'islandora/object/%islandora_object/download_mods_as_marcxml' => array(
      'title' => 'Download MARCXML',
      'type' => MENU_CALLBACK,
      'page callback' => 'islandora_marcxml_transform_mods_to_marcxml',
      'page arguments' => array(2),
      'access callback' => 'islandora_marcxml_access_callback',
      'access arguments' => array(2),
      'delivery callback' => 'islandora_marcxml_xml_download',
      'file' => 'islandora_marcxml.inc',
    ),
  );
}

/**
 * Delivery callback used to download the output as XML.
 */
function islandora_marcxml_xml_download($output) {
  drupal_add_http_header('Content-type', 'text/xml;charset=utf8');
  drupal_add_http_header('Content-length', strlen($output));
  drupal_add_http_header('Content-Disposition', 'attachment; filename="marc.xml"');

  print $output;

  drupal_page_footer();
}

/**
 * Access callback.
 *
 * Requires that the given object contains a MODS datastream (and to be
 * viewable, as per the stock permissions).
 */
function islandora_marcxml_access_callback($object) {
  if (!$object) {
    return FALSE;
  }

  return user_access(FEDORA_VIEW) && isset($object['MODS']);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_marcxml_islandora_ingest_steps(array $configuration) {
  if (isset($configuration['models'])) {
    $dsids = islandora_get_datastreams_requirements_from_models((array)$configuration['models']);
    if (isset($dsids['MODS'])) {
      return array(
        array(
          'type' => 'form',
          'weight' => -5,
          'form_id' => 'islandora_marcxml_file_form',
          'args' => array(),
          'file' => 'includes/file.form.inc',
          'module' => 'islandora_marcxml',
        ),
      );
    }
  }
}

